/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowBookResponse } from '../models/borrow-book-response';
export interface PageResponseBorrowBookResponse {
  content?: Array<BorrowBookResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
